const crud_form_user_types = {
  POST_NEW_USER: "POST_NEW_USER",
  SUCCESS_POST_NEW_USER: "SUCCESS_POST_NEW_USER",
  FAIL_POST_NEW_USER: "FAIL_POST_NEW_USER", 
  LOGOUT_USER: "LOGOUT_USER",
  SUCCESS_LOGOUT_USER: "SUCCESS_LOGOUT_USER",
  FAIL_LOGOUT: "FAIL_LOGOUT"
};

export default crud_form_user_types;