const crud_form_project_types = { 
  POST_NEW_PROJECT: "POST_NEW_PROJECT",
  LOADING_POST_NEW_PROJECT: "LOADING_POST_NEW_PROJECT",
  SUCCESS_POST_NEW_PROJECT: "SUCCESS_POST_NEW_PROJECT",
  FAIL_POST_NEW_PROJECT: "FAIL_POST_NEW_PROJECT", 

  GET_PROJECT: "GET_PROJECT",
  LOADING_GET_PROJECT: "LOADING_GET_PROJECT",
  SUCCESS_GET_PROJECT: "SUCCESS_GET_PROJECT",
  FAIL_GET_PROJECT: "FAIL_GET_PROJECT", 

  POST_PROJECT_IMPORT_URL: "POST_PROJECT_IMPORT_URL",
  SUCCESS_POST_PROJECT_IMPORT_URL: "SUCCESS_POST_PROJECT_IMPORT_URL",
  FAIL_POST_PROJECT_IMPORT_URL: "FAIL_POST_PROJECT_IMPORT_URL"
};

export default crud_form_project_types;